locals {
  location = lookup(var.regions, var.loc, "uksouth")
  rg_name  = "rg-${var.short}-${var.loc}-${terraform.workspace}-001"
  kv_name  = "kv-${var.short}-${var.loc}-${terraform.workspace}-001"
}

data "azurerm_client_config" "current" {}

module "tags" {
  source  = "libre-devops/tags/azurerm"
  version = "~> 4.0"

  cost_centre     = "1888/67"
  owner           = "platform@example.com"
  deployed_branch = var.deployed_branch
  deployed_repo   = var.deployed_repo
}

module "rg" {
  source  = "libre-devops/rg/azurerm"
  version = "~> 4.0"

  resource_groups = [{ name = local.rg_name, location = local.location, tags = module.tags.tags }]
}

# A vault to hold the secret. Access policies (not RBAC) grant the caller secret access so the write
# works immediately (no RBAC propagation wait). purge_protection is off only so the example is
# disposable; leave it at the default (true) for real vaults.
module "keyvault" {
  source  = "libre-devops/keyvault/azurerm"
  version = "~> 4.0"

  resource_group_id = module.rg.ids[local.rg_name]
  location          = local.location
  tags              = module.tags.tags

  key_vaults = {
    (local.kv_name) = {
      rbac_authorization_enabled = false
      purge_protection_enabled   = false
      access_policies = [
        {
          object_id          = data.azurerm_client_config.current.object_id
          secret_permissions = ["Get", "List", "Set", "Delete", "Recover", "Purge"]
        }
      ]
    }
  }
}

# Minimal call: one generated secret. The value is generated by an ephemeral random_password inside the
# module and written through value_wo, so it is stored in the vault but never in Terraform state.
module "keyvault_secret" {
  source = "../../"

  key_vault_id = module.keyvault.ids[local.kv_name]
  tags         = module.tags.tags

  secrets = {
    "example-generated" = { generate = true }
  }
}
