locals {
  location = lookup(var.regions, var.loc, "uksouth")
  rg_name  = "rg-${var.short}-${var.loc}-${terraform.workspace}-001"
  kv_name  = "kv-${var.short}-${var.loc}-${terraform.workspace}-001"
}

data "azurerm_client_config" "current" {}

# The runner's public egress IP, so it can be allow-listed on the vault firewall (this subscription
# enforces default-deny network rules on key vaults, so the writer's IP must be permitted).
module "runner_ip" {
  source  = "libre-devops/get-ip-address/external"
  version = "~> 4.0"
}

module "tags" {
  source  = "libre-devops/tags/azurerm"
  version = "~> 4.0"

  cost_centre     = "1888/67"
  owner           = "platform@example.com"
  deployed_branch = var.deployed_branch
  deployed_repo   = var.deployed_repo
}

module "rg" {
  source  = "libre-devops/rg/azurerm"
  version = "~> 4.0"

  resource_groups = [{ name = local.rg_name, location = local.location, tags = module.tags.tags }]
}

# A vault to hold the secret. Access policies (not RBAC) grant the caller secret access so the write
# works immediately (no RBAC propagation wait), and the runner IP is allow-listed so the data-plane
# write is not blocked by the firewall. purge_protection is off only so the example is disposable.
module "keyvault" {
  source  = "libre-devops/keyvault/azurerm"
  version = "~> 4.0"

  resource_group_id = module.rg.ids[local.rg_name]
  location          = local.location
  tags              = module.tags.tags

  key_vaults = {
    (local.kv_name) = {
      rbac_authorization_enabled = false
      purge_protection_enabled   = false
      network_acls = {
        default_action = "Deny"
        bypass         = "AzureServices"
        ip_rules       = ["${module.runner_ip.public_ip_address}/32"]
      }
      access_policies = [
        {
          object_id          = data.azurerm_client_config.current.object_id
          secret_permissions = ["Get", "List", "Set", "Delete", "Recover", "Purge"]
        }
      ]
    }
  }
}

# Give the vault firewall rule a moment to take effect before the data-plane secret write.
resource "time_sleep" "kv_firewall" {
  create_duration = "60s"

  triggers = {
    vault = module.keyvault.ids[local.kv_name]
    ip    = module.runner_ip.public_ip_address
  }
}

# Minimal call: one generated secret. The value is generated by an ephemeral random_password inside the
# module and written through value_wo, so it is stored in the vault but never in Terraform state.
module "keyvault_secret" {
  source = "../../"

  key_vault_id = module.keyvault.ids[local.kv_name]
  tags         = module.tags.tags

  secrets = {
    "example-generated" = { generate = true }
  }

  depends_on = [time_sleep.kv_firewall]
}
